function [ f ] = NewFigure( name )
    f = figure(                 ...
        'Name', name            ...
        ,'NumberTitle', 'off'   ...
        ,'Units', 'normalized'  ...
        ,'OuterPosition', [0 0 1 1]);
    pause(0.00001);
    frame_h = get(f, 'JavaFrame');
    set(frame_h                 ...
        ,'Maximized', 1); 
end